### ISSUE TITLE
Cannot unlock windows at all and controls are not working except for volume button

### ISSUE THREAD

**Issue by UntrndSpartn** [Valkirie/HandheldCompanion#1058]
**Device manufacturer**
- [x] VALVE

**Device model**
Steamdeck 64gb

**Handheld Companion Version**
Not sure, the newest as of may 6th 2024

**Describe the bug**
I downloaded HC as a way to use my steamdeck like, well, a steamdeck but with windows 11 instead of SteamOS. I downloaded it, tried to unlock it and found i could not use the touchscreen, any external devices, the steamdecks controls except for the power button and volume buttons.

**To Reproduce**
N/A

**Expected behavior**
I expected it to work like normal except i could use the steamdecks controller with games

**Logs files**
N/A

**Comment by CasperH2O** [comment]
Hey @UntrndSpartn , thanks for dropping in. That does'nt sound good at all. While installing HC did everything go alright? Did you reboot at the end of the installer?

Did you upgrade/update from an older version, say 3-4 months old? Because this problem sound a lot like the HidHide uninstall softbrick issue we had then. #817

The recovery instructions are here: https://docs.nefarius.at/projects/HidHide/fixing-a-bricked-system/

**Comment by CasperH2O** [comment]
@UntrndSpartn did you manage to recover?

**Comment by CasperH2O** [comment]
No reply from original issue creator. Information provided, closing ticket.
