### ISSUE TITLE
Start automatically with Windows results in greyed-out Connect

### ISSUE THREAD

**Issue by themiracy** [Valkirie/HandheldCompanion#300]
![image](https://user-images.githubusercontent.com/103528993/203429569-2e71200f-9682-4b01-84c9-23300a8ff65c.png)

In Windows 11 Pro, 22621.898, when HC is set to start automatically with Windows, most of the time, the Connect/Disconnect is in the Connect label state and greyed out. Clicking on it does not do anything. There does not appear to be a way to fix this inside the app, but quitting and re-starting causes it to behave correctly.

I am going to try next to change the Task Scheduler startup item for the app to wait 30-60 seconds to see if it resolves this.

**Comment by CasperH2O** [comment]
I've seen this also with older builds, but not the most recent one. Could be because the physical gamepad is not yet connected when HC is starting. My solution was to stop / start service in the bottom left corner of the main GUI.

Also the connect/disconnect button has been changed/improved for the upcoming release (0.13.x.x).

**Comment by CasperH2O** [comment]
@themiracy do you still have this problem with the 0.13 release?

**Comment by CasperH2O** [comment]
This part of HC received a large update for 0.15. Have personally not seen this issue anymore. As ticket initiator has not replied, closing this one. Feel free to reopen if issue reoccurs.
