### ISSUE TITLE
HC does not work well with Microsoft XBOX game pass games

### ISSUE THREAD

**Issue by vskllee** [Valkirie/HandheldCompanion#652]
This software can not set Microsoft XGP game switch Xbox controller mode, because XGP game directory permission problems caused by can not be set, request to improve support Microsoft XGP gamepad!

**Comment by vskllee** [comment]
> 嘿@vskllee谢谢你报道这个。你能更具体地告诉我们什么是微软XGP游戏吗？控制器停止工作了吗？你收到任何错误消息吗？

The name of this game is "Naraka: Bladepoint", Microsoft XGP game, any game downloaded with the Xbox app under Windows 11, can not be used to set the controller mode with the controller companion, the reason is "no permission to access this program"! Not one game, but all Microsoft XGP games can't set Xbox controller mode!

**Comment by CasperH2O** [comment]
@vskllee can you share a screenshot of your Controller configuration in HC main GUI page? It's the page that has a large picture of a controller (xbox or ds4).

**Comment by marceloadsj** [comment]
PS: let me know if I can help with any more information, logs, whatever you need. 🙏  :)

**Comment by marceloadsj** [comment]
Just to say that I managed to configure the gyro for Doom Eternal. It required "exact" steps to be recognized.

 **1) Create the profile:**
- open HC and make sure the service is running
- add a hotkey to the gamepad to open the quick tools
- open the game and put it in window mode
- then, open the quick tools via the gamepad hotkey
- check if it is displaying the game executable
- now, on the third tab (at the bottom of the quick tools), enable the "use profile", and enable the "universal control"
- this will make the HC to create a profile for that executable

When doing that, I created a profile for the Handheld Companion executable by mistake. Now it's impossible to delete it because it says "the executable is running". 😅 

**2) Configure the profile:**
- you can, now, close the game so all options for that profile became available
- for me, I did not have to use XInput checkbox (like The Phawnx mentioned)
- also, I left gyro etc enabled by default on that profile
- and, I removed the hotkey to open quick tools
- and also, you can put the game back to fullscreen

One thing I noticed is that, when I open the game, if the "last selected app" right before the game is opened, is not HC, then the gyro stops working.

When it happens, I have to minimize the game, open the HC app from the tray, then maximize the game again.

**Comment by Valkirie** [comment]
You can either create the profile from quicktools.
![image](https://github.com/Valkirie/HandheldCompanion/assets/934757/17ec841b-96a3-4283-98b4-697a34a743c1)

OR, you need to pick the UWP AppxManifest.xml file rather than trying to pick the executable which is fully locked by Windows.
![image](https://github.com/Valkirie/HandheldCompanion/assets/934757/5c40f99d-0dae-4b52-98b5-f61c3f90553a)

**Comment by Valkirie** [comment]
Should be improved by: https://github.com/Valkirie/HandheldCompanion/commit/999679d865293b2915d56f638aaa81d56c914e96

**Comment by CasperH2O** [comment]
See also the wiki page on using HC with Xbox Game Pass: https://github.com/Valkirie/HandheldCompanion/wiki/Xbox-Live-Gamepass.

If you feel like the instructions can be improved, feel free to do so. :)

**Comment by Valkirie** [comment]
> 

Done: https://github.com/Valkirie/HandheldCompanion/wiki/Xbox-Live-Gamepass

**Comment by CasperH2O** [comment]
@vskllee do above instructions help you set up your XGP games?

**Comment by CasperH2O** [comment]
@vskllee we just released 0.16.2.3, can you check if ot works for you?

**Comment by kennedyoliveira** [comment]
Having issues with Game Pass games as well, although a bit different then what is report in this ticket.

After installing a GP game and opening it for the first time, I go to the quick tools and create a profile, setup controller and other configs and everything works as expected, but if I close the game and open it again, or the computer sleeps/hibernates, when it comes back the controller no longer works, I have to go to HC main window and disconnect the virtual controller and un-hide the original one for the game to pick up again.

This happened with the games Sea of Stars, Lies of P and Hi-Fi Rush.

Also noticed that the game recognizes the controller is there, in all of the above games when you press any button in the controller it shows the icons of the controller, for example when it stops working if I change from xbox controller to ps4, it will update the icons in game, but it will not do anything.

I'm using a fully updated Rog Ally on the latest BIOS.

**Comment by CasperH2O** [comment]
The controller detection problem can be fixed by using the extended controller compatibility in the settings (current release) or with the live slot swapping feature currently being beta tested. 

Closing this ticket as there is a proper solution and improved method on the way.
